/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { type Mesh } from 'three'
import { AxesHelper } from 'three'

type GLTFResult = GLTF & {
    nodes: {
        geometry_0: Mesh
    }
    //materials: {}
}

const modelPath = '/assets/3d-models/office_texture_test1.glb'

const DeskModel: React.FC<React.JSX.IntrinsicElements['group']> = (props) => {

    const { nodes/*, materials*/ } = useGLTF(modelPath) as unknown as GLTFResult

    const originHelper = useMemo(() => {
        // red = x-axis, green = y-axis, blue = z-axis
        const helper = new AxesHelper(1)
        return helper
    }, [])

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.geometry_0.geometry}
                material={nodes.geometry_0.material}
                position={[0, 0, 0]}
            />
            <primitive object={originHelper} />
        </group>
    )
}

export default DeskModel

useGLTF.preload(modelPath)